name: Lint and Merge

on:
  pull_request:
    branches:
      - develop  

  push:
    branches:
      - develop 

jobs:
  lint_and_merge:
    runs-on: ubuntu-22.04 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (versão 20.x)
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.20.0

      - name: Add pnpm to PATH
        run: echo "$HOME/.pnpm/bin" >> $GITHUB_PATH # Adiciona o pnpm ao PATH

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Merge develop into main (if lint passes and on push to develop)
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout main
          git merge develop --no-ff -m "Merge develop into main"
          git push
